torso_pitch_joint: 0
head_yaw_joint: 0
head_pitch_joint: 0
l_shoulder_pitch_joint: 0
l_shoulder_roll_joint: 0
l_elbow_pitch_joint: 0
l_elbow_yaw_joint: 0
r_shoulder_pitch_joint: 0
r_shoulder_roll_joint: 0
r_elbow_pitch_joint: 0
r_elbow_yaw_joint: 0
l_hip_yaw_joint: 0
l_hip_roll_joint: 0
l_hip_pitch_joint: 0
l_ankle_pitch_joint: 0
l_ankle_roll_joint: 0
r_hip_yaw_joint: 0
r_hip_roll_joint: 0
r_hip_pitch_joint: 0
r_ankle_pitch_joint: 0
r_ankle_roll_joint: 0