# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robinion_gui.ui',
# licensing of 'robinion_gui.ui' applies.
#
# Created: Thu Feb  4 11:26:28 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 681, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_walking = QtWidgets.QWidget()
        self.tab_walking.setObjectName("tab_walking")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_walking)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 671, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelGaitState = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelGaitState.setFont(font)
        self.labelGaitState.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGaitState.setObjectName("labelGaitState")
        self.verticalLayout_2.addWidget(self.labelGaitState)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButtonZeroPose = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonZeroPose.setObjectName("pushButtonZeroPose")
        self.verticalLayout_2.addWidget(self.pushButtonZeroPose)
        self.pushButtonInitialize = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonInitialize.setObjectName("pushButtonInitialize")
        self.verticalLayout_2.addWidget(self.pushButtonInitialize)
        self.pushButtonStanding = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStanding.setObjectName("pushButtonStanding")
        self.verticalLayout_2.addWidget(self.pushButtonStanding)
        self.pushButtonStartWalk = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStartWalk.setObjectName("pushButtonStartWalk")
        self.verticalLayout_2.addWidget(self.pushButtonStartWalk)
        self.pushButtonStopWalk = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStopWalk.setObjectName("pushButtonStopWalk")
        self.verticalLayout_2.addWidget(self.pushButtonStopWalk)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelGaitCommand = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelGaitCommand.setFont(font)
        self.labelGaitCommand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGaitCommand.setObjectName("labelGaitCommand")
        self.verticalLayout_3.addWidget(self.labelGaitCommand)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonForward = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.horizontalLayout_6.addWidget(self.pushButtonForward)
        self.pushButtonBackward = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonBackward.setObjectName("pushButtonBackward")
        self.horizontalLayout_6.addWidget(self.pushButtonBackward)
        self.labelCmdX = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdX.setObjectName("labelCmdX")
        self.horizontalLayout_6.addWidget(self.labelCmdX)
        self.horizontalSliderCmdX = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdX.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdX.setObjectName("horizontalSliderCmdX")
        self.horizontalLayout_6.addWidget(self.horizontalSliderCmdX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonSideLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSideLeft.setObjectName("pushButtonSideLeft")
        self.horizontalLayout_7.addWidget(self.pushButtonSideLeft)
        self.pushButtonSideRight = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSideRight.setObjectName("pushButtonSideRight")
        self.horizontalLayout_7.addWidget(self.pushButtonSideRight)
        self.labelCmdY = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdY.setObjectName("labelCmdY")
        self.horizontalLayout_7.addWidget(self.labelCmdY)
        self.horizontalSliderCmdY = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdY.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdY.setObjectName("horizontalSliderCmdY")
        self.horizontalLayout_7.addWidget(self.horizontalSliderCmdY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonTurnLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonTurnLeft.setObjectName("pushButtonTurnLeft")
        self.horizontalLayout_5.addWidget(self.pushButtonTurnLeft)
        self.pushButtonTurnRight = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonTurnRight.setObjectName("pushButtonTurnRight")
        self.horizontalLayout_5.addWidget(self.pushButtonTurnRight)
        self.labelCmdA = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdA.setObjectName("labelCmdA")
        self.horizontalLayout_5.addWidget(self.labelCmdA)
        self.horizontalSliderCmdA = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdA.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdA.setObjectName("horizontalSliderCmdA")
        self.horizontalLayout_5.addWidget(self.horizontalSliderCmdA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_walking, "")
        self.tab_manipulation = QtWidgets.QWidget()
        self.tab_manipulation.setObjectName("tab_manipulation")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_manipulation)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 10, 671, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelGetPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelGetPose.setFont(font)
        self.labelGetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGetPose.setObjectName("labelGetPose")
        self.verticalLayout_4.addWidget(self.labelGetPose)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelGYaw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGYaw.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGYaw.setObjectName("labelGYaw")
        self.gridLayout.addWidget(self.labelGYaw, 6, 0, 1, 1)
        self.labelGPitch = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPitch.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPitch.setObjectName("labelGPitch")
        self.gridLayout.addWidget(self.labelGPitch, 5, 0, 1, 1)
        self.labelGX = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGX.setObjectName("labelGX")
        self.gridLayout.addWidget(self.labelGX, 1, 0, 1, 1)
        self.labelGZ = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGZ.setObjectName("labelGZ")
        self.gridLayout.addWidget(self.labelGZ, 3, 0, 1, 1)
        self.labelGRoll = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGRoll.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGRoll.setObjectName("labelGRoll")
        self.gridLayout.addWidget(self.labelGRoll, 4, 0, 1, 1)
        self.labelGY = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGY.setObjectName("labelGY")
        self.gridLayout.addWidget(self.labelGY, 2, 0, 1, 1)
        self.lineEditCurrentLHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandYaw.setObjectName("lineEditCurrentLHandYaw")
        self.gridLayout.addWidget(self.lineEditCurrentLHandYaw, 6, 1, 1, 1)
        self.lineEditCurrentRHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandYaw.setObjectName("lineEditCurrentRHandYaw")
        self.gridLayout.addWidget(self.lineEditCurrentRHandYaw, 6, 2, 1, 1)
        self.labelGPRHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPRHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPRHand.setObjectName("labelGPRHand")
        self.gridLayout.addWidget(self.labelGPRHand, 0, 2, 1, 1)
        self.labelGPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPose.setObjectName("labelGPose")
        self.gridLayout.addWidget(self.labelGPose, 0, 0, 1, 1)
        self.labelGPLHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPLHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPLHand.setObjectName("labelGPLHand")
        self.gridLayout.addWidget(self.labelGPLHand, 0, 1, 1, 1)
        self.pushButtonGetRHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonGetRHandPose.setObjectName("pushButtonGetRHandPose")
        self.gridLayout.addWidget(self.pushButtonGetRHandPose, 7, 2, 1, 1)
        self.pushButtonGetLHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonGetLHandPose.setObjectName("pushButtonGetLHandPose")
        self.gridLayout.addWidget(self.pushButtonGetLHandPose, 7, 1, 1, 1)
        self.lineEditCurrentLHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandPitch.setObjectName("lineEditCurrentLHandPitch")
        self.gridLayout.addWidget(self.lineEditCurrentLHandPitch, 5, 1, 1, 1)
        self.lineEditCurrentRHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandPitch.setObjectName("lineEditCurrentRHandPitch")
        self.gridLayout.addWidget(self.lineEditCurrentRHandPitch, 5, 2, 1, 1)
        self.lineEditCurrentLHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandRoll.setObjectName("lineEditCurrentLHandRoll")
        self.gridLayout.addWidget(self.lineEditCurrentLHandRoll, 4, 1, 1, 1)
        self.lineEditCurrentRHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandRoll.setObjectName("lineEditCurrentRHandRoll")
        self.gridLayout.addWidget(self.lineEditCurrentRHandRoll, 4, 2, 1, 1)
        self.lineEditCurrentLHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandZ.setObjectName("lineEditCurrentLHandZ")
        self.gridLayout.addWidget(self.lineEditCurrentLHandZ, 3, 1, 1, 1)
        self.lineEditCurrentRHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandZ.setObjectName("lineEditCurrentRHandZ")
        self.gridLayout.addWidget(self.lineEditCurrentRHandZ, 3, 2, 1, 1)
        self.lineEditCurrentLHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandY.setObjectName("lineEditCurrentLHandY")
        self.gridLayout.addWidget(self.lineEditCurrentLHandY, 2, 1, 1, 1)
        self.lineEditCurrentRHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandY.setObjectName("lineEditCurrentRHandY")
        self.gridLayout.addWidget(self.lineEditCurrentRHandY, 2, 2, 1, 1)
        self.lineEditCurrentLHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandX.setObjectName("lineEditCurrentLHandX")
        self.gridLayout.addWidget(self.lineEditCurrentLHandX, 1, 1, 1, 1)
        self.lineEditCurrentRHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandX.setObjectName("lineEditCurrentRHandX")
        self.gridLayout.addWidget(self.lineEditCurrentRHandX, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelSetPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelSetPose.setFont(font)
        self.labelSetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSetPose.setObjectName("labelSetPose")
        self.verticalLayout_6.addWidget(self.labelSetPose)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSYaw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSYaw.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSYaw.setObjectName("labelSYaw")
        self.gridLayout_2.addWidget(self.labelSYaw, 6, 0, 1, 1)
        self.labelSPitch = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPitch.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPitch.setObjectName("labelSPitch")
        self.gridLayout_2.addWidget(self.labelSPitch, 5, 0, 1, 1)
        self.labelSX = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSX.setObjectName("labelSX")
        self.gridLayout_2.addWidget(self.labelSX, 1, 0, 1, 1)
        self.labelSZ = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSZ.setObjectName("labelSZ")
        self.gridLayout_2.addWidget(self.labelSZ, 3, 0, 1, 1)
        self.labelSRoll = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSRoll.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSRoll.setObjectName("labelSRoll")
        self.gridLayout_2.addWidget(self.labelSRoll, 4, 0, 1, 1)
        self.labelSY = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSY.setObjectName("labelSY")
        self.gridLayout_2.addWidget(self.labelSY, 2, 0, 1, 1)
        self.lineEditSetLHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandYaw.setObjectName("lineEditSetLHandYaw")
        self.gridLayout_2.addWidget(self.lineEditSetLHandYaw, 6, 1, 1, 1)
        self.lineEditSetRHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandYaw.setObjectName("lineEditSetRHandYaw")
        self.gridLayout_2.addWidget(self.lineEditSetRHandYaw, 6, 2, 1, 1)
        self.labelSPRHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPRHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPRHand.setObjectName("labelSPRHand")
        self.gridLayout_2.addWidget(self.labelSPRHand, 0, 2, 1, 1)
        self.labelSPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPose.setObjectName("labelSPose")
        self.gridLayout_2.addWidget(self.labelSPose, 0, 0, 1, 1)
        self.labelSPLHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPLHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPLHand.setObjectName("labelSPLHand")
        self.gridLayout_2.addWidget(self.labelSPLHand, 0, 1, 1, 1)
        self.pushButtonSetRHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSetRHandPose.setObjectName("pushButtonSetRHandPose")
        self.gridLayout_2.addWidget(self.pushButtonSetRHandPose, 7, 2, 1, 1)
        self.pushButtonSetLHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSetLHandPose.setObjectName("pushButtonSetLHandPose")
        self.gridLayout_2.addWidget(self.pushButtonSetLHandPose, 7, 1, 1, 1)
        self.lineEditSetLHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandX.setObjectName("lineEditSetLHandX")
        self.gridLayout_2.addWidget(self.lineEditSetLHandX, 1, 1, 1, 1)
        self.lineEditSetRHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandX.setObjectName("lineEditSetRHandX")
        self.gridLayout_2.addWidget(self.lineEditSetRHandX, 1, 2, 1, 1)
        self.lineEditSetLHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandY.setObjectName("lineEditSetLHandY")
        self.gridLayout_2.addWidget(self.lineEditSetLHandY, 2, 1, 1, 1)
        self.lineEditSetRHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandY.setObjectName("lineEditSetRHandY")
        self.gridLayout_2.addWidget(self.lineEditSetRHandY, 2, 2, 1, 1)
        self.lineEditSetLHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandZ.setObjectName("lineEditSetLHandZ")
        self.gridLayout_2.addWidget(self.lineEditSetLHandZ, 3, 1, 1, 1)
        self.lineEditSetRHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandZ.setObjectName("lineEditSetRHandZ")
        self.gridLayout_2.addWidget(self.lineEditSetRHandZ, 3, 2, 1, 1)
        self.lineEditSetLHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandRoll.setObjectName("lineEditSetLHandRoll")
        self.gridLayout_2.addWidget(self.lineEditSetLHandRoll, 4, 1, 1, 1)
        self.lineEditSetRHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandRoll.setObjectName("lineEditSetRHandRoll")
        self.gridLayout_2.addWidget(self.lineEditSetRHandRoll, 4, 2, 1, 1)
        self.lineEditSetLHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandPitch.setObjectName("lineEditSetLHandPitch")
        self.gridLayout_2.addWidget(self.lineEditSetLHandPitch, 5, 1, 1, 1)
        self.lineEditSetRHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandPitch.setObjectName("lineEditSetRHandPitch")
        self.gridLayout_2.addWidget(self.lineEditSetRHandPitch, 5, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_manipulation, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Robinion GUI Controller", None, -1))
        self.labelGaitState.setText(QtWidgets.QApplication.translate("MainWindow", "Gait State", None, -1))
        self.pushButtonZeroPose.setText(QtWidgets.QApplication.translate("MainWindow", "Zero Pose", None, -1))
        self.pushButtonInitialize.setText(QtWidgets.QApplication.translate("MainWindow", "Initialize", None, -1))
        self.pushButtonStanding.setText(QtWidgets.QApplication.translate("MainWindow", "Standing", None, -1))
        self.pushButtonStartWalk.setText(QtWidgets.QApplication.translate("MainWindow", "Start Walk", None, -1))
        self.pushButtonStopWalk.setText(QtWidgets.QApplication.translate("MainWindow", "Stop Walk", None, -1))
        self.labelGaitCommand.setText(QtWidgets.QApplication.translate("MainWindow", "Gait Command", None, -1))
        self.pushButtonForward.setText(QtWidgets.QApplication.translate("MainWindow", "Forward", None, -1))
        self.pushButtonBackward.setText(QtWidgets.QApplication.translate("MainWindow", "Backward", None, -1))
        self.labelCmdX.setText(QtWidgets.QApplication.translate("MainWindow", "CMD_X", None, -1))
        self.pushButtonSideLeft.setText(QtWidgets.QApplication.translate("MainWindow", "Side Left", None, -1))
        self.pushButtonSideRight.setText(QtWidgets.QApplication.translate("MainWindow", "Side Right", None, -1))
        self.labelCmdY.setText(QtWidgets.QApplication.translate("MainWindow", "CMD_Y", None, -1))
        self.pushButtonTurnLeft.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Left", None, -1))
        self.pushButtonTurnRight.setText(QtWidgets.QApplication.translate("MainWindow", "Turn Right", None, -1))
        self.labelCmdA.setText(QtWidgets.QApplication.translate("MainWindow", "CMD_A", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_walking), QtWidgets.QApplication.translate("MainWindow", "Gait Controller", None, -1))
        self.labelGetPose.setText(QtWidgets.QApplication.translate("MainWindow", "Get Pose", None, -1))
        self.labelGYaw.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.labelGPitch.setText(QtWidgets.QApplication.translate("MainWindow", "P", None, -1))
        self.labelGX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.labelGZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.labelGRoll.setText(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.labelGY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.labelGPRHand.setText(QtWidgets.QApplication.translate("MainWindow", "Right Hand", None, -1))
        self.labelGPose.setText(QtWidgets.QApplication.translate("MainWindow", "Pose", None, -1))
        self.labelGPLHand.setText(QtWidgets.QApplication.translate("MainWindow", "Left Hand", None, -1))
        self.pushButtonGetRHandPose.setText(QtWidgets.QApplication.translate("MainWindow", "Get Right Hand Pose", None, -1))
        self.pushButtonGetLHandPose.setText(QtWidgets.QApplication.translate("MainWindow", "Get Left Hand Pose", None, -1))
        self.labelSetPose.setText(QtWidgets.QApplication.translate("MainWindow", "Set Pose", None, -1))
        self.labelSYaw.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.labelSPitch.setText(QtWidgets.QApplication.translate("MainWindow", "P", None, -1))
        self.labelSX.setText(QtWidgets.QApplication.translate("MainWindow", "X", None, -1))
        self.labelSZ.setText(QtWidgets.QApplication.translate("MainWindow", "Z", None, -1))
        self.labelSRoll.setText(QtWidgets.QApplication.translate("MainWindow", "R", None, -1))
        self.labelSY.setText(QtWidgets.QApplication.translate("MainWindow", "Y", None, -1))
        self.labelSPRHand.setText(QtWidgets.QApplication.translate("MainWindow", "Right Hand", None, -1))
        self.labelSPose.setText(QtWidgets.QApplication.translate("MainWindow", "Pose", None, -1))
        self.labelSPLHand.setText(QtWidgets.QApplication.translate("MainWindow", "Left Hand", None, -1))
        self.pushButtonSetRHandPose.setText(QtWidgets.QApplication.translate("MainWindow", "Set Right Hand Pose", None, -1))
        self.pushButtonSetLHandPose.setText(QtWidgets.QApplication.translate("MainWindow", "Set Left Hand Pose", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manipulation), QtWidgets.QApplication.translate("MainWindow", "Manipulation Module", None, -1))

