# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robinion_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 681, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_walking = QtWidgets.QWidget()
        self.tab_walking.setObjectName("tab_walking")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_walking)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 671, 221))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelGaitState = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelGaitState.setFont(font)
        self.labelGaitState.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGaitState.setObjectName("labelGaitState")
        self.verticalLayout_2.addWidget(self.labelGaitState)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.pushButtonZeroPose = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonZeroPose.setObjectName("pushButtonZeroPose")
        self.verticalLayout_2.addWidget(self.pushButtonZeroPose)
        self.pushButtonInitialize = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonInitialize.setObjectName("pushButtonInitialize")
        self.verticalLayout_2.addWidget(self.pushButtonInitialize)
        self.pushButtonStanding = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStanding.setObjectName("pushButtonStanding")
        self.verticalLayout_2.addWidget(self.pushButtonStanding)
        self.pushButtonStartWalk = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStartWalk.setObjectName("pushButtonStartWalk")
        self.verticalLayout_2.addWidget(self.pushButtonStartWalk)
        self.pushButtonStopWalk = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonStopWalk.setObjectName("pushButtonStopWalk")
        self.verticalLayout_2.addWidget(self.pushButtonStopWalk)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelGaitCommand = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelGaitCommand.setFont(font)
        self.labelGaitCommand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGaitCommand.setObjectName("labelGaitCommand")
        self.verticalLayout_3.addWidget(self.labelGaitCommand)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButtonForward = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.horizontalLayout_6.addWidget(self.pushButtonForward)
        self.pushButtonBackward = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonBackward.setObjectName("pushButtonBackward")
        self.horizontalLayout_6.addWidget(self.pushButtonBackward)
        self.labelCmdX = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdX.setObjectName("labelCmdX")
        self.horizontalLayout_6.addWidget(self.labelCmdX)
        self.horizontalSliderCmdX = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdX.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdX.setObjectName("horizontalSliderCmdX")
        self.horizontalLayout_6.addWidget(self.horizontalSliderCmdX)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonSideLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSideLeft.setObjectName("pushButtonSideLeft")
        self.horizontalLayout_7.addWidget(self.pushButtonSideLeft)
        self.pushButtonSideRight = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSideRight.setObjectName("pushButtonSideRight")
        self.horizontalLayout_7.addWidget(self.pushButtonSideRight)
        self.labelCmdY = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdY.setObjectName("labelCmdY")
        self.horizontalLayout_7.addWidget(self.labelCmdY)
        self.horizontalSliderCmdY = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdY.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdY.setObjectName("horizontalSliderCmdY")
        self.horizontalLayout_7.addWidget(self.horizontalSliderCmdY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonTurnLeft = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonTurnLeft.setObjectName("pushButtonTurnLeft")
        self.horizontalLayout_5.addWidget(self.pushButtonTurnLeft)
        self.pushButtonTurnRight = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonTurnRight.setObjectName("pushButtonTurnRight")
        self.horizontalLayout_5.addWidget(self.pushButtonTurnRight)
        self.labelCmdA = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.labelCmdA.setObjectName("labelCmdA")
        self.horizontalLayout_5.addWidget(self.labelCmdA)
        self.horizontalSliderCmdA = QtWidgets.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSliderCmdA.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCmdA.setObjectName("horizontalSliderCmdA")
        self.horizontalLayout_5.addWidget(self.horizontalSliderCmdA)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_walking, "")
        self.tab_gait_parameter = QtWidgets.QWidget()
        self.tab_gait_parameter.setObjectName("tab_gait_parameter")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_gait_parameter)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 20, 161, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelLImit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLImit.setFont(font)
        self.labelLImit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLImit.setObjectName("labelLImit")
        self.verticalLayout_5.addWidget(self.labelLImit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dSB_max_vx = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_max_vx.setDecimals(3)
        self.dSB_max_vx.setMinimum(-99.99)
        self.dSB_max_vx.setSingleStep(0.01)
        self.dSB_max_vx.setObjectName("dSB_max_vx")
        self.gridLayout_3.addWidget(self.dSB_max_vx, 1, 1, 1, 1)
        self.label_max_vx = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_max_vx.setObjectName("label_max_vx")
        self.gridLayout_3.addWidget(self.label_max_vx, 1, 0, 1, 1)
        self.label_min_vy = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_min_vy.setObjectName("label_min_vy")
        self.gridLayout_3.addWidget(self.label_min_vy, 2, 0, 1, 1)
        self.dSB_min_va = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_min_va.setDecimals(3)
        self.dSB_min_va.setMinimum(-99.99)
        self.dSB_min_va.setSingleStep(0.01)
        self.dSB_min_va.setObjectName("dSB_min_va")
        self.gridLayout_3.addWidget(self.dSB_min_va, 4, 1, 1, 1)
        self.label_max_vy = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_max_vy.setObjectName("label_max_vy")
        self.gridLayout_3.addWidget(self.label_max_vy, 3, 0, 1, 1)
        self.label_min_vx = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_min_vx.setObjectName("label_min_vx")
        self.gridLayout_3.addWidget(self.label_min_vx, 0, 0, 1, 1)
        self.dSB_min_vx = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_min_vx.setDecimals(3)
        self.dSB_min_vx.setMinimum(-99.99)
        self.dSB_min_vx.setSingleStep(0.01)
        self.dSB_min_vx.setObjectName("dSB_min_vx")
        self.gridLayout_3.addWidget(self.dSB_min_vx, 0, 1, 1, 1)
        self.dSB_max_vy = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_max_vy.setDecimals(3)
        self.dSB_max_vy.setMinimum(-99.99)
        self.dSB_max_vy.setSingleStep(0.01)
        self.dSB_max_vy.setObjectName("dSB_max_vy")
        self.gridLayout_3.addWidget(self.dSB_max_vy, 3, 1, 1, 1)
        self.dSB_min_vy = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_min_vy.setDecimals(3)
        self.dSB_min_vy.setMinimum(-99.99)
        self.dSB_min_vy.setSingleStep(0.01)
        self.dSB_min_vy.setObjectName("dSB_min_vy")
        self.gridLayout_3.addWidget(self.dSB_min_vy, 2, 1, 1, 1)
        self.label_min_va = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_min_va.setObjectName("label_min_va")
        self.gridLayout_3.addWidget(self.label_min_va, 4, 0, 1, 1)
        self.label_max_va = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_max_va.setObjectName("label_max_va")
        self.gridLayout_3.addWidget(self.label_max_va, 5, 0, 1, 1)
        self.dSB_max_va = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.dSB_max_va.setDecimals(3)
        self.dSB_max_va.setMinimum(-99.99)
        self.dSB_max_va.setSingleStep(0.01)
        self.dSB_max_va.setObjectName("dSB_max_va")
        self.gridLayout_3.addWidget(self.dSB_max_va, 5, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_gait_parameter)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(290, 20, 331, 243))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.labelParameter = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelParameter.setFont(font)
        self.labelParameter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParameter.setObjectName("labelParameter")
        self.verticalLayout_7.addWidget(self.labelParameter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_t_step = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_t_step.setObjectName("label_t_step")
        self.gridLayout_4.addWidget(self.label_t_step, 1, 0, 1, 1)
        self.dSB_rb_t_step = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_t_step.setDecimals(3)
        self.dSB_rb_t_step.setMinimum(-99.99)
        self.dSB_rb_t_step.setSingleStep(0.01)
        self.dSB_rb_t_step.setObjectName("dSB_rb_t_step")
        self.gridLayout_4.addWidget(self.dSB_rb_t_step, 1, 2, 1, 1)
        self.label_support_x = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_support_x.setObjectName("label_support_x")
        self.gridLayout_4.addWidget(self.label_support_x, 4, 0, 1, 1)
        self.dSB_rb_dsp_ratio = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_dsp_ratio.setDecimals(3)
        self.dSB_rb_dsp_ratio.setMinimum(-99.99)
        self.dSB_rb_dsp_ratio.setSingleStep(0.01)
        self.dSB_rb_dsp_ratio.setObjectName("dSB_rb_dsp_ratio")
        self.gridLayout_4.addWidget(self.dSB_rb_dsp_ratio, 2, 2, 1, 1)
        self.labelParameterName = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParameterName.setFont(font)
        self.labelParameterName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParameterName.setObjectName("labelParameterName")
        self.gridLayout_4.addWidget(self.labelParameterName, 0, 0, 1, 1)
        self.label_swing_foot_height = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_swing_foot_height.setObjectName("label_swing_foot_height")
        self.gridLayout_4.addWidget(self.label_swing_foot_height, 3, 0, 1, 1)
        self.label_support_y = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_support_y.setObjectName("label_support_y")
        self.gridLayout_4.addWidget(self.label_support_y, 5, 0, 1, 1)
        self.labelParameterGazebo = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParameterGazebo.setFont(font)
        self.labelParameterGazebo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParameterGazebo.setObjectName("labelParameterGazebo")
        self.gridLayout_4.addWidget(self.labelParameterGazebo, 0, 1, 1, 1)
        self.labelParameterRobot = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelParameterRobot.setFont(font)
        self.labelParameterRobot.setAlignment(QtCore.Qt.AlignCenter)
        self.labelParameterRobot.setObjectName("labelParameterRobot")
        self.gridLayout_4.addWidget(self.labelParameterRobot, 0, 2, 1, 1)
        self.label_dsp_ratio = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_dsp_ratio.setObjectName("label_dsp_ratio")
        self.gridLayout_4.addWidget(self.label_dsp_ratio, 2, 0, 1, 1)
        self.dSB_gz_dsp_ratio = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_dsp_ratio.setDecimals(3)
        self.dSB_gz_dsp_ratio.setMinimum(-99.99)
        self.dSB_gz_dsp_ratio.setSingleStep(0.01)
        self.dSB_gz_dsp_ratio.setObjectName("dSB_gz_dsp_ratio")
        self.gridLayout_4.addWidget(self.dSB_gz_dsp_ratio, 2, 1, 1, 1)
        self.dSB_gz_t_step = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_t_step.setDecimals(3)
        self.dSB_gz_t_step.setMinimum(-99.99)
        self.dSB_gz_t_step.setSingleStep(0.01)
        self.dSB_gz_t_step.setObjectName("dSB_gz_t_step")
        self.gridLayout_4.addWidget(self.dSB_gz_t_step, 1, 1, 1, 1)
        self.label_body_tilt = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_body_tilt.setObjectName("label_body_tilt")
        self.gridLayout_4.addWidget(self.label_body_tilt, 6, 0, 1, 1)
        self.dSB_gz_swing_foot_height = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_swing_foot_height.setDecimals(3)
        self.dSB_gz_swing_foot_height.setMinimum(-99.99)
        self.dSB_gz_swing_foot_height.setSingleStep(0.01)
        self.dSB_gz_swing_foot_height.setObjectName("dSB_gz_swing_foot_height")
        self.gridLayout_4.addWidget(self.dSB_gz_swing_foot_height, 3, 1, 1, 1)
        self.dSB_gz_support_x = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_support_x.setDecimals(3)
        self.dSB_gz_support_x.setMinimum(-99.99)
        self.dSB_gz_support_x.setSingleStep(0.01)
        self.dSB_gz_support_x.setObjectName("dSB_gz_support_x")
        self.gridLayout_4.addWidget(self.dSB_gz_support_x, 4, 1, 1, 1)
        self.dSB_gz_support_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_support_y.setDecimals(3)
        self.dSB_gz_support_y.setMinimum(-99.99)
        self.dSB_gz_support_y.setSingleStep(0.01)
        self.dSB_gz_support_y.setObjectName("dSB_gz_support_y")
        self.gridLayout_4.addWidget(self.dSB_gz_support_y, 5, 1, 1, 1)
        self.dSB_gz_body_tilt = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_gz_body_tilt.setDecimals(3)
        self.dSB_gz_body_tilt.setMinimum(-99.99)
        self.dSB_gz_body_tilt.setSingleStep(0.01)
        self.dSB_gz_body_tilt.setObjectName("dSB_gz_body_tilt")
        self.gridLayout_4.addWidget(self.dSB_gz_body_tilt, 6, 1, 1, 1)
        self.dSB_rb_swing_foot_height = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_swing_foot_height.setDecimals(3)
        self.dSB_rb_swing_foot_height.setMinimum(-99.99)
        self.dSB_rb_swing_foot_height.setSingleStep(0.01)
        self.dSB_rb_swing_foot_height.setObjectName("dSB_rb_swing_foot_height")
        self.gridLayout_4.addWidget(self.dSB_rb_swing_foot_height, 3, 2, 1, 1)
        self.dSB_rb_support_x = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_support_x.setDecimals(3)
        self.dSB_rb_support_x.setMinimum(-99.99)
        self.dSB_rb_support_x.setSingleStep(0.01)
        self.dSB_rb_support_x.setObjectName("dSB_rb_support_x")
        self.gridLayout_4.addWidget(self.dSB_rb_support_x, 4, 2, 1, 1)
        self.dSB_rb_support_y = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_support_y.setDecimals(3)
        self.dSB_rb_support_y.setMinimum(-99.99)
        self.dSB_rb_support_y.setSingleStep(0.01)
        self.dSB_rb_support_y.setObjectName("dSB_rb_support_y")
        self.gridLayout_4.addWidget(self.dSB_rb_support_y, 5, 2, 1, 1)
        self.dSB_rb_body_tilt = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_3)
        self.dSB_rb_body_tilt.setDecimals(3)
        self.dSB_rb_body_tilt.setMinimum(-99.99)
        self.dSB_rb_body_tilt.setSingleStep(0.01)
        self.dSB_rb_body_tilt.setObjectName("dSB_rb_body_tilt")
        self.gridLayout_4.addWidget(self.dSB_rb_body_tilt, 6, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.pushButtonLoadParameter = QtWidgets.QPushButton(self.tab_gait_parameter)
        self.pushButtonLoadParameter.setGeometry(QtCore.QRect(290, 280, 141, 41))
        self.pushButtonLoadParameter.setObjectName("pushButtonLoadParameter")
        self.pushButtonSaveParameter = QtWidgets.QPushButton(self.tab_gait_parameter)
        self.pushButtonSaveParameter.setGeometry(QtCore.QRect(480, 280, 141, 41))
        self.pushButtonSaveParameter.setObjectName("pushButtonSaveParameter")
        self.tabWidget.addTab(self.tab_gait_parameter, "")
        self.tab_manipulation = QtWidgets.QWidget()
        self.tab_manipulation.setObjectName("tab_manipulation")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_manipulation)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(1, 10, 671, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelGetPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelGetPose.setFont(font)
        self.labelGetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGetPose.setObjectName("labelGetPose")
        self.verticalLayout_4.addWidget(self.labelGetPose)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelGYaw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGYaw.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGYaw.setObjectName("labelGYaw")
        self.gridLayout.addWidget(self.labelGYaw, 6, 0, 1, 1)
        self.labelGPitch = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPitch.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPitch.setObjectName("labelGPitch")
        self.gridLayout.addWidget(self.labelGPitch, 5, 0, 1, 1)
        self.labelGX = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGX.setObjectName("labelGX")
        self.gridLayout.addWidget(self.labelGX, 1, 0, 1, 1)
        self.labelGZ = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGZ.setObjectName("labelGZ")
        self.gridLayout.addWidget(self.labelGZ, 3, 0, 1, 1)
        self.labelGRoll = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGRoll.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGRoll.setObjectName("labelGRoll")
        self.gridLayout.addWidget(self.labelGRoll, 4, 0, 1, 1)
        self.labelGY = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGY.setObjectName("labelGY")
        self.gridLayout.addWidget(self.labelGY, 2, 0, 1, 1)
        self.lineEditCurrentLHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandYaw.setObjectName("lineEditCurrentLHandYaw")
        self.gridLayout.addWidget(self.lineEditCurrentLHandYaw, 6, 1, 1, 1)
        self.lineEditCurrentRHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandYaw.setObjectName("lineEditCurrentRHandYaw")
        self.gridLayout.addWidget(self.lineEditCurrentRHandYaw, 6, 2, 1, 1)
        self.labelGPRHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPRHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPRHand.setObjectName("labelGPRHand")
        self.gridLayout.addWidget(self.labelGPRHand, 0, 2, 1, 1)
        self.labelGPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPose.setObjectName("labelGPose")
        self.gridLayout.addWidget(self.labelGPose, 0, 0, 1, 1)
        self.labelGPLHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelGPLHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGPLHand.setObjectName("labelGPLHand")
        self.gridLayout.addWidget(self.labelGPLHand, 0, 1, 1, 1)
        self.pushButtonGetRHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonGetRHandPose.setObjectName("pushButtonGetRHandPose")
        self.gridLayout.addWidget(self.pushButtonGetRHandPose, 7, 2, 1, 1)
        self.pushButtonGetLHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonGetLHandPose.setObjectName("pushButtonGetLHandPose")
        self.gridLayout.addWidget(self.pushButtonGetLHandPose, 7, 1, 1, 1)
        self.lineEditCurrentLHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandPitch.setObjectName("lineEditCurrentLHandPitch")
        self.gridLayout.addWidget(self.lineEditCurrentLHandPitch, 5, 1, 1, 1)
        self.lineEditCurrentRHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandPitch.setObjectName("lineEditCurrentRHandPitch")
        self.gridLayout.addWidget(self.lineEditCurrentRHandPitch, 5, 2, 1, 1)
        self.lineEditCurrentLHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandRoll.setObjectName("lineEditCurrentLHandRoll")
        self.gridLayout.addWidget(self.lineEditCurrentLHandRoll, 4, 1, 1, 1)
        self.lineEditCurrentRHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandRoll.setObjectName("lineEditCurrentRHandRoll")
        self.gridLayout.addWidget(self.lineEditCurrentRHandRoll, 4, 2, 1, 1)
        self.lineEditCurrentLHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandZ.setObjectName("lineEditCurrentLHandZ")
        self.gridLayout.addWidget(self.lineEditCurrentLHandZ, 3, 1, 1, 1)
        self.lineEditCurrentRHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandZ.setObjectName("lineEditCurrentRHandZ")
        self.gridLayout.addWidget(self.lineEditCurrentRHandZ, 3, 2, 1, 1)
        self.lineEditCurrentLHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandY.setObjectName("lineEditCurrentLHandY")
        self.gridLayout.addWidget(self.lineEditCurrentLHandY, 2, 1, 1, 1)
        self.lineEditCurrentRHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandY.setObjectName("lineEditCurrentRHandY")
        self.gridLayout.addWidget(self.lineEditCurrentRHandY, 2, 2, 1, 1)
        self.lineEditCurrentLHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentLHandX.setObjectName("lineEditCurrentLHandX")
        self.gridLayout.addWidget(self.lineEditCurrentLHandX, 1, 1, 1, 1)
        self.lineEditCurrentRHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditCurrentRHandX.setObjectName("lineEditCurrentRHandX")
        self.gridLayout.addWidget(self.lineEditCurrentRHandX, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelSetPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelSetPose.setFont(font)
        self.labelSetPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSetPose.setObjectName("labelSetPose")
        self.verticalLayout_6.addWidget(self.labelSetPose)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSYaw = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSYaw.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSYaw.setObjectName("labelSYaw")
        self.gridLayout_2.addWidget(self.labelSYaw, 6, 0, 1, 1)
        self.labelSPitch = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPitch.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPitch.setObjectName("labelSPitch")
        self.gridLayout_2.addWidget(self.labelSPitch, 5, 0, 1, 1)
        self.labelSX = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSX.setObjectName("labelSX")
        self.gridLayout_2.addWidget(self.labelSX, 1, 0, 1, 1)
        self.labelSZ = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSZ.setObjectName("labelSZ")
        self.gridLayout_2.addWidget(self.labelSZ, 3, 0, 1, 1)
        self.labelSRoll = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSRoll.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSRoll.setObjectName("labelSRoll")
        self.gridLayout_2.addWidget(self.labelSRoll, 4, 0, 1, 1)
        self.labelSY = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSY.setObjectName("labelSY")
        self.gridLayout_2.addWidget(self.labelSY, 2, 0, 1, 1)
        self.lineEditSetLHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandYaw.setObjectName("lineEditSetLHandYaw")
        self.gridLayout_2.addWidget(self.lineEditSetLHandYaw, 6, 1, 1, 1)
        self.lineEditSetRHandYaw = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandYaw.setObjectName("lineEditSetRHandYaw")
        self.gridLayout_2.addWidget(self.lineEditSetRHandYaw, 6, 2, 1, 1)
        self.labelSPRHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPRHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPRHand.setObjectName("labelSPRHand")
        self.gridLayout_2.addWidget(self.labelSPRHand, 0, 2, 1, 1)
        self.labelSPose = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPose.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPose.setObjectName("labelSPose")
        self.gridLayout_2.addWidget(self.labelSPose, 0, 0, 1, 1)
        self.labelSPLHand = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelSPLHand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSPLHand.setObjectName("labelSPLHand")
        self.gridLayout_2.addWidget(self.labelSPLHand, 0, 1, 1, 1)
        self.pushButtonSetRHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSetRHandPose.setObjectName("pushButtonSetRHandPose")
        self.gridLayout_2.addWidget(self.pushButtonSetRHandPose, 7, 2, 1, 1)
        self.pushButtonSetLHandPose = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonSetLHandPose.setObjectName("pushButtonSetLHandPose")
        self.gridLayout_2.addWidget(self.pushButtonSetLHandPose, 7, 1, 1, 1)
        self.lineEditSetLHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandX.setObjectName("lineEditSetLHandX")
        self.gridLayout_2.addWidget(self.lineEditSetLHandX, 1, 1, 1, 1)
        self.lineEditSetRHandX = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandX.setObjectName("lineEditSetRHandX")
        self.gridLayout_2.addWidget(self.lineEditSetRHandX, 1, 2, 1, 1)
        self.lineEditSetLHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandY.setObjectName("lineEditSetLHandY")
        self.gridLayout_2.addWidget(self.lineEditSetLHandY, 2, 1, 1, 1)
        self.lineEditSetRHandY = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandY.setObjectName("lineEditSetRHandY")
        self.gridLayout_2.addWidget(self.lineEditSetRHandY, 2, 2, 1, 1)
        self.lineEditSetLHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandZ.setObjectName("lineEditSetLHandZ")
        self.gridLayout_2.addWidget(self.lineEditSetLHandZ, 3, 1, 1, 1)
        self.lineEditSetRHandZ = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandZ.setObjectName("lineEditSetRHandZ")
        self.gridLayout_2.addWidget(self.lineEditSetRHandZ, 3, 2, 1, 1)
        self.lineEditSetLHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandRoll.setObjectName("lineEditSetLHandRoll")
        self.gridLayout_2.addWidget(self.lineEditSetLHandRoll, 4, 1, 1, 1)
        self.lineEditSetRHandRoll = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandRoll.setObjectName("lineEditSetRHandRoll")
        self.gridLayout_2.addWidget(self.lineEditSetRHandRoll, 4, 2, 1, 1)
        self.lineEditSetLHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetLHandPitch.setObjectName("lineEditSetLHandPitch")
        self.gridLayout_2.addWidget(self.lineEditSetLHandPitch, 5, 1, 1, 1)
        self.lineEditSetRHandPitch = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEditSetRHandPitch.setObjectName("lineEditSetRHandPitch")
        self.gridLayout_2.addWidget(self.lineEditSetRHandPitch, 5, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_manipulation, "")
        self.tab_head = QtWidgets.QWidget()
        self.tab_head.setObjectName("tab_head")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_head)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 29, 611, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hS_HeadYawCommand = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.hS_HeadYawCommand.setMinimum(-314)
        self.hS_HeadYawCommand.setMaximum(314)
        self.hS_HeadYawCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_HeadYawCommand.setObjectName("hS_HeadYawCommand")
        self.gridLayout_5.addWidget(self.hS_HeadYawCommand, 2, 1, 1, 1)
        self.labelHeadYaw = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelHeadYaw.setObjectName("labelHeadYaw")
        self.gridLayout_5.addWidget(self.labelHeadYaw, 2, 0, 1, 1)
        self.labelHeadPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelHeadPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeadPitchCurrent.setObjectName("labelHeadPitchCurrent")
        self.gridLayout_5.addWidget(self.labelHeadPitchCurrent, 3, 2, 1, 1)
        self.labelHeadYawCurrent = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelHeadYawCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeadYawCurrent.setObjectName("labelHeadYawCurrent")
        self.gridLayout_5.addWidget(self.labelHeadYawCurrent, 2, 2, 1, 1)
        self.labelHeadPitch = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.labelHeadPitch.setObjectName("labelHeadPitch")
        self.gridLayout_5.addWidget(self.labelHeadPitch, 3, 0, 1, 1)
        self.labelHeadJointValue = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelHeadJointValue.setFont(font)
        self.labelHeadJointValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeadJointValue.setObjectName("labelHeadJointValue")
        self.gridLayout_5.addWidget(self.labelHeadJointValue, 0, 2, 1, 1)
        self.hS_HeadPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_3)
        self.hS_HeadPitchCommand.setMinimum(-314)
        self.hS_HeadPitchCommand.setMaximum(314)
        self.hS_HeadPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_HeadPitchCommand.setObjectName("hS_HeadPitchCommand")
        self.gridLayout_5.addWidget(self.hS_HeadPitchCommand, 3, 1, 1, 1)
        self.labelHeadJointCommand = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelHeadJointCommand.setFont(font)
        self.labelHeadJointCommand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeadJointCommand.setObjectName("labelHeadJointCommand")
        self.gridLayout_5.addWidget(self.labelHeadJointCommand, 0, 1, 1, 1)
        self.labelHeadJointName = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelHeadJointName.setFont(font)
        self.labelHeadJointName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeadJointName.setObjectName("labelHeadJointName")
        self.gridLayout_5.addWidget(self.labelHeadJointName, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_head, "")
        self.tab_arm = QtWidgets.QWidget()
        self.tab_arm.setObjectName("tab_arm")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_arm)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 30, 611, 231))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelLElbowPitch = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLElbowPitch.setObjectName("labelLElbowPitch")
        self.gridLayout_6.addWidget(self.labelLElbowPitch, 4, 0, 1, 1)
        self.labelRShoulderRoll = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRShoulderRoll.setObjectName("labelRShoulderRoll")
        self.gridLayout_6.addWidget(self.labelRShoulderRoll, 7, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 1, 0, 1, 1)
        self.hS_LShoulderPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_LShoulderPitchCommand.setMinimum(-314)
        self.hS_LShoulderPitchCommand.setMaximum(314)
        self.hS_LShoulderPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LShoulderPitchCommand.setObjectName("hS_LShoulderPitchCommand")
        self.gridLayout_6.addWidget(self.hS_LShoulderPitchCommand, 2, 1, 1, 1)
        self.labelLShoulderPitch = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLShoulderPitch.setObjectName("labelLShoulderPitch")
        self.gridLayout_6.addWidget(self.labelLShoulderPitch, 2, 0, 1, 1)
        self.labelLShoulderPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLShoulderPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLShoulderPitchCurrent.setObjectName("labelLShoulderPitchCurrent")
        self.gridLayout_6.addWidget(self.labelLShoulderPitchCurrent, 2, 2, 1, 1)
        self.labelLShoulderRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLShoulderRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLShoulderRollCurrent.setObjectName("labelLShoulderRollCurrent")
        self.gridLayout_6.addWidget(self.labelLShoulderRollCurrent, 3, 2, 1, 1)
        self.labelRShoulderPitch = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRShoulderPitch.setObjectName("labelRShoulderPitch")
        self.gridLayout_6.addWidget(self.labelRShoulderPitch, 6, 0, 1, 1)
        self.labelRElbowPitch = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRElbowPitch.setObjectName("labelRElbowPitch")
        self.gridLayout_6.addWidget(self.labelRElbowPitch, 8, 0, 1, 1)
        self.labelArmJointName = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelArmJointName.setFont(font)
        self.labelArmJointName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArmJointName.setObjectName("labelArmJointName")
        self.gridLayout_6.addWidget(self.labelArmJointName, 0, 0, 1, 1)
        self.labelLShoulderRoll = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLShoulderRoll.setObjectName("labelLShoulderRoll")
        self.gridLayout_6.addWidget(self.labelLShoulderRoll, 3, 0, 1, 1)
        self.labelLElbowYaw = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLElbowYaw.setObjectName("labelLElbowYaw")
        self.gridLayout_6.addWidget(self.labelLElbowYaw, 5, 0, 1, 1)
        self.labelArmJointValue = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelArmJointValue.setFont(font)
        self.labelArmJointValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArmJointValue.setObjectName("labelArmJointValue")
        self.gridLayout_6.addWidget(self.labelArmJointValue, 0, 2, 1, 1)
        self.labelArmJointCommand = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelArmJointCommand.setFont(font)
        self.labelArmJointCommand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelArmJointCommand.setObjectName("labelArmJointCommand")
        self.gridLayout_6.addWidget(self.labelArmJointCommand, 0, 1, 1, 1)
        self.labelRElbowYaw = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRElbowYaw.setObjectName("labelRElbowYaw")
        self.gridLayout_6.addWidget(self.labelRElbowYaw, 9, 0, 1, 1)
        self.hS_LShoulderRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_LShoulderRollCommand.setMinimum(-314)
        self.hS_LShoulderRollCommand.setMaximum(314)
        self.hS_LShoulderRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LShoulderRollCommand.setObjectName("hS_LShoulderRollCommand")
        self.gridLayout_6.addWidget(self.hS_LShoulderRollCommand, 3, 1, 1, 1)
        self.hS_LElbowPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_LElbowPitchCommand.setMinimum(-314)
        self.hS_LElbowPitchCommand.setMaximum(314)
        self.hS_LElbowPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LElbowPitchCommand.setObjectName("hS_LElbowPitchCommand")
        self.gridLayout_6.addWidget(self.hS_LElbowPitchCommand, 4, 1, 1, 1)
        self.hS_LElbowYawCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_LElbowYawCommand.setMinimum(-314)
        self.hS_LElbowYawCommand.setMaximum(314)
        self.hS_LElbowYawCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LElbowYawCommand.setObjectName("hS_LElbowYawCommand")
        self.gridLayout_6.addWidget(self.hS_LElbowYawCommand, 5, 1, 1, 1)
        self.hS_RShoulderPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_RShoulderPitchCommand.setMinimum(-314)
        self.hS_RShoulderPitchCommand.setMaximum(314)
        self.hS_RShoulderPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RShoulderPitchCommand.setObjectName("hS_RShoulderPitchCommand")
        self.gridLayout_6.addWidget(self.hS_RShoulderPitchCommand, 6, 1, 1, 1)
        self.hS_RShoulderRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_RShoulderRollCommand.setMinimum(-314)
        self.hS_RShoulderRollCommand.setMaximum(314)
        self.hS_RShoulderRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RShoulderRollCommand.setObjectName("hS_RShoulderRollCommand")
        self.gridLayout_6.addWidget(self.hS_RShoulderRollCommand, 7, 1, 1, 1)
        self.hS_RElbowPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_RElbowPitchCommand.setMinimum(-314)
        self.hS_RElbowPitchCommand.setMaximum(314)
        self.hS_RElbowPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RElbowPitchCommand.setObjectName("hS_RElbowPitchCommand")
        self.gridLayout_6.addWidget(self.hS_RElbowPitchCommand, 8, 1, 1, 1)
        self.hS_RElbowYawCommand = QtWidgets.QSlider(self.gridLayoutWidget_4)
        self.hS_RElbowYawCommand.setMinimum(-314)
        self.hS_RElbowYawCommand.setMaximum(314)
        self.hS_RElbowYawCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RElbowYawCommand.setObjectName("hS_RElbowYawCommand")
        self.gridLayout_6.addWidget(self.hS_RElbowYawCommand, 9, 1, 1, 1)
        self.labelLElbowPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLElbowPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLElbowPitchCurrent.setObjectName("labelLElbowPitchCurrent")
        self.gridLayout_6.addWidget(self.labelLElbowPitchCurrent, 4, 2, 1, 1)
        self.labelLElbowYawCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelLElbowYawCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLElbowYawCurrent.setObjectName("labelLElbowYawCurrent")
        self.gridLayout_6.addWidget(self.labelLElbowYawCurrent, 5, 2, 1, 1)
        self.labelRShoulderPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRShoulderPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRShoulderPitchCurrent.setObjectName("labelRShoulderPitchCurrent")
        self.gridLayout_6.addWidget(self.labelRShoulderPitchCurrent, 6, 2, 1, 1)
        self.labelRShoulderRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRShoulderRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRShoulderRollCurrent.setObjectName("labelRShoulderRollCurrent")
        self.gridLayout_6.addWidget(self.labelRShoulderRollCurrent, 7, 2, 1, 1)
        self.labelRElbowPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRElbowPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRElbowPitchCurrent.setObjectName("labelRElbowPitchCurrent")
        self.gridLayout_6.addWidget(self.labelRElbowPitchCurrent, 8, 2, 1, 1)
        self.labelRElbowYawCurrent = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.labelRElbowYawCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRElbowYawCurrent.setObjectName("labelRElbowYawCurrent")
        self.gridLayout_6.addWidget(self.labelRElbowYawCurrent, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_arm, "")
        self.tab_leg = QtWidgets.QWidget()
        self.tab_leg.setObjectName("tab_leg")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_leg)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 30, 611, 281))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.labelLAnklePitch = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLAnklePitch.setObjectName("labelLAnklePitch")
        self.gridLayout_7.addWidget(self.labelLAnklePitch, 5, 0, 1, 1)
        self.labelRAnklePitch = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRAnklePitch.setObjectName("labelRAnklePitch")
        self.gridLayout_7.addWidget(self.labelRAnklePitch, 10, 0, 1, 1)
        self.hS_RHipRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_RHipRollCommand.setMinimum(-314)
        self.hS_RHipRollCommand.setMaximum(314)
        self.hS_RHipRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RHipRollCommand.setObjectName("hS_RHipRollCommand")
        self.gridLayout_7.addWidget(self.hS_RHipRollCommand, 8, 1, 1, 1)
        self.labelRHipPitch = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipPitch.setObjectName("labelRHipPitch")
        self.gridLayout_7.addWidget(self.labelRHipPitch, 9, 0, 1, 1)
        self.hS_LAnkleRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_LAnkleRollCommand.setMinimum(-314)
        self.hS_LAnkleRollCommand.setMaximum(314)
        self.hS_LAnkleRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LAnkleRollCommand.setObjectName("hS_LAnkleRollCommand")
        self.gridLayout_7.addWidget(self.hS_LAnkleRollCommand, 6, 1, 1, 1)
        self.hS_LHipRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_LHipRollCommand.setMinimum(-314)
        self.hS_LHipRollCommand.setMaximum(314)
        self.hS_LHipRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LHipRollCommand.setObjectName("hS_LHipRollCommand")
        self.gridLayout_7.addWidget(self.hS_LHipRollCommand, 3, 1, 1, 1)
        self.hS_RHipPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_RHipPitchCommand.setMinimum(-314)
        self.hS_RHipPitchCommand.setMaximum(314)
        self.hS_RHipPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RHipPitchCommand.setObjectName("hS_RHipPitchCommand")
        self.gridLayout_7.addWidget(self.hS_RHipPitchCommand, 9, 1, 1, 1)
        self.labelLAnkleRoll = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLAnkleRoll.setObjectName("labelLAnkleRoll")
        self.gridLayout_7.addWidget(self.labelLAnkleRoll, 6, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 1, 0, 1, 1)
        self.labelLHipYaw = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipYaw.setObjectName("labelLHipYaw")
        self.gridLayout_7.addWidget(self.labelLHipYaw, 2, 0, 1, 1)
        self.labelRHipYaw = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipYaw.setObjectName("labelRHipYaw")
        self.gridLayout_7.addWidget(self.labelRHipYaw, 7, 0, 1, 1)
        self.labelLHipRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLHipRollCurrent.setObjectName("labelLHipRollCurrent")
        self.gridLayout_7.addWidget(self.labelLHipRollCurrent, 3, 2, 1, 1)
        self.labelLHipPitch = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipPitch.setObjectName("labelLHipPitch")
        self.gridLayout_7.addWidget(self.labelLHipPitch, 4, 0, 1, 1)
        self.labelLegJointValue = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLegJointValue.setFont(font)
        self.labelLegJointValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLegJointValue.setObjectName("labelLegJointValue")
        self.gridLayout_7.addWidget(self.labelLegJointValue, 0, 2, 1, 1)
        self.labelRHipPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRHipPitchCurrent.setObjectName("labelRHipPitchCurrent")
        self.gridLayout_7.addWidget(self.labelRHipPitchCurrent, 9, 2, 1, 1)
        self.labelRHipRoll = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipRoll.setObjectName("labelRHipRoll")
        self.gridLayout_7.addWidget(self.labelRHipRoll, 8, 0, 1, 1)
        self.hS_LHipPitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_LHipPitchCommand.setMinimum(-314)
        self.hS_LHipPitchCommand.setMaximum(314)
        self.hS_LHipPitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LHipPitchCommand.setObjectName("hS_LHipPitchCommand")
        self.gridLayout_7.addWidget(self.hS_LHipPitchCommand, 4, 1, 1, 1)
        self.hS_RAnklePitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_RAnklePitchCommand.setMinimum(-314)
        self.hS_RAnklePitchCommand.setMaximum(314)
        self.hS_RAnklePitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RAnklePitchCommand.setObjectName("hS_RAnklePitchCommand")
        self.gridLayout_7.addWidget(self.hS_RAnklePitchCommand, 10, 1, 1, 1)
        self.hS_LAnklePitchCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_LAnklePitchCommand.setMinimum(-314)
        self.hS_LAnklePitchCommand.setMaximum(314)
        self.hS_LAnklePitchCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LAnklePitchCommand.setObjectName("hS_LAnklePitchCommand")
        self.gridLayout_7.addWidget(self.hS_LAnklePitchCommand, 5, 1, 1, 1)
        self.labelRHipRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRHipRollCurrent.setObjectName("labelRHipRollCurrent")
        self.gridLayout_7.addWidget(self.labelRHipRollCurrent, 8, 2, 1, 1)
        self.labelRAnklePitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRAnklePitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRAnklePitchCurrent.setObjectName("labelRAnklePitchCurrent")
        self.gridLayout_7.addWidget(self.labelRAnklePitchCurrent, 10, 2, 1, 1)
        self.labelLegJointName = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLegJointName.setFont(font)
        self.labelLegJointName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLegJointName.setObjectName("labelLegJointName")
        self.gridLayout_7.addWidget(self.labelLegJointName, 0, 0, 1, 1)
        self.hS_LHipYawCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_LHipYawCommand.setMinimum(-314)
        self.hS_LHipYawCommand.setMaximum(314)
        self.hS_LHipYawCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_LHipYawCommand.setObjectName("hS_LHipYawCommand")
        self.gridLayout_7.addWidget(self.hS_LHipYawCommand, 2, 1, 1, 1)
        self.labelLHipRoll = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipRoll.setObjectName("labelLHipRoll")
        self.gridLayout_7.addWidget(self.labelLHipRoll, 3, 0, 1, 1)
        self.labelLegJointCommand = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLegJointCommand.setFont(font)
        self.labelLegJointCommand.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLegJointCommand.setObjectName("labelLegJointCommand")
        self.gridLayout_7.addWidget(self.labelLegJointCommand, 0, 1, 1, 1)
        self.labelLAnkleRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLAnkleRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLAnkleRollCurrent.setObjectName("labelLAnkleRollCurrent")
        self.gridLayout_7.addWidget(self.labelLAnkleRollCurrent, 6, 2, 1, 1)
        self.hS_RHipYawCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_RHipYawCommand.setMinimum(-314)
        self.hS_RHipYawCommand.setMaximum(314)
        self.hS_RHipYawCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RHipYawCommand.setObjectName("hS_RHipYawCommand")
        self.gridLayout_7.addWidget(self.hS_RHipYawCommand, 7, 1, 1, 1)
        self.labelLAnklePitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLAnklePitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLAnklePitchCurrent.setObjectName("labelLAnklePitchCurrent")
        self.gridLayout_7.addWidget(self.labelLAnklePitchCurrent, 5, 2, 1, 1)
        self.labelLHipYawCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipYawCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLHipYawCurrent.setObjectName("labelLHipYawCurrent")
        self.gridLayout_7.addWidget(self.labelLHipYawCurrent, 2, 2, 1, 1)
        self.labelLHipPitchCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelLHipPitchCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLHipPitchCurrent.setObjectName("labelLHipPitchCurrent")
        self.gridLayout_7.addWidget(self.labelLHipPitchCurrent, 4, 2, 1, 1)
        self.labelRHipYawCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRHipYawCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRHipYawCurrent.setObjectName("labelRHipYawCurrent")
        self.gridLayout_7.addWidget(self.labelRHipYawCurrent, 7, 2, 1, 1)
        self.labelRAnkleRoll = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRAnkleRoll.setObjectName("labelRAnkleRoll")
        self.gridLayout_7.addWidget(self.labelRAnkleRoll, 11, 0, 1, 1)
        self.hS_RAnkleRollCommand = QtWidgets.QSlider(self.gridLayoutWidget_5)
        self.hS_RAnkleRollCommand.setMinimum(-314)
        self.hS_RAnkleRollCommand.setMaximum(314)
        self.hS_RAnkleRollCommand.setOrientation(QtCore.Qt.Horizontal)
        self.hS_RAnkleRollCommand.setObjectName("hS_RAnkleRollCommand")
        self.gridLayout_7.addWidget(self.hS_RAnkleRollCommand, 11, 1, 1, 1)
        self.labelRAnkleRollCurrent = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelRAnkleRollCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRAnkleRollCurrent.setObjectName("labelRAnkleRollCurrent")
        self.gridLayout_7.addWidget(self.labelRAnkleRollCurrent, 11, 2, 1, 1)
        self.tabWidget.addTab(self.tab_leg, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robinion GUI Controller"))
        self.labelGaitState.setText(_translate("MainWindow", "Gait State"))
        self.pushButtonZeroPose.setText(_translate("MainWindow", "Zero Pose"))
        self.pushButtonInitialize.setText(_translate("MainWindow", "Initialize"))
        self.pushButtonStanding.setText(_translate("MainWindow", "Standing"))
        self.pushButtonStartWalk.setText(_translate("MainWindow", "Start Walk"))
        self.pushButtonStopWalk.setText(_translate("MainWindow", "Stop Walk"))
        self.labelGaitCommand.setText(_translate("MainWindow", "Gait Command"))
        self.pushButtonForward.setText(_translate("MainWindow", "Forward"))
        self.pushButtonBackward.setText(_translate("MainWindow", "Backward"))
        self.labelCmdX.setText(_translate("MainWindow", "CMD_X"))
        self.pushButtonSideLeft.setText(_translate("MainWindow", "Side Left"))
        self.pushButtonSideRight.setText(_translate("MainWindow", "Side Right"))
        self.labelCmdY.setText(_translate("MainWindow", "CMD_Y"))
        self.pushButtonTurnLeft.setText(_translate("MainWindow", "Turn Left"))
        self.pushButtonTurnRight.setText(_translate("MainWindow", "Turn Right"))
        self.labelCmdA.setText(_translate("MainWindow", "CMD_A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_walking), _translate("MainWindow", "Gait Controller"))
        self.labelLImit.setText(_translate("MainWindow", "Limit"))
        self.label_max_vx.setText(_translate("MainWindow", "max_vx"))
        self.label_min_vy.setText(_translate("MainWindow", "min_vy"))
        self.label_max_vy.setText(_translate("MainWindow", "max_vy"))
        self.label_min_vx.setText(_translate("MainWindow", "min_vx"))
        self.label_min_va.setText(_translate("MainWindow", "min_va"))
        self.label_max_va.setText(_translate("MainWindow", "max_va"))
        self.labelParameter.setText(_translate("MainWindow", "Parameter"))
        self.label_t_step.setText(_translate("MainWindow", "t_step"))
        self.label_support_x.setText(_translate("MainWindow", "support_x"))
        self.labelParameterName.setText(_translate("MainWindow", "Name"))
        self.label_swing_foot_height.setText(_translate("MainWindow", "swing_foot_height"))
        self.label_support_y.setText(_translate("MainWindow", "support_y"))
        self.labelParameterGazebo.setText(_translate("MainWindow", "Gazebo"))
        self.labelParameterRobot.setText(_translate("MainWindow", "Robot"))
        self.label_dsp_ratio.setText(_translate("MainWindow", "dsp_ratio"))
        self.label_body_tilt.setText(_translate("MainWindow", "body_tilt"))
        self.pushButtonLoadParameter.setText(_translate("MainWindow", "Load Parameter"))
        self.pushButtonSaveParameter.setText(_translate("MainWindow", "Save Parameter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_gait_parameter), _translate("MainWindow", "Gait Parameter"))
        self.labelGetPose.setText(_translate("MainWindow", "Get Pose"))
        self.labelGYaw.setText(_translate("MainWindow", "Y"))
        self.labelGPitch.setText(_translate("MainWindow", "P"))
        self.labelGX.setText(_translate("MainWindow", "X"))
        self.labelGZ.setText(_translate("MainWindow", "Z"))
        self.labelGRoll.setText(_translate("MainWindow", "R"))
        self.labelGY.setText(_translate("MainWindow", "Y"))
        self.labelGPRHand.setText(_translate("MainWindow", "Right Hand"))
        self.labelGPose.setText(_translate("MainWindow", "Pose"))
        self.labelGPLHand.setText(_translate("MainWindow", "Left Hand"))
        self.pushButtonGetRHandPose.setText(_translate("MainWindow", "Get Right Hand Pose"))
        self.pushButtonGetLHandPose.setText(_translate("MainWindow", "Get Left Hand Pose"))
        self.labelSetPose.setText(_translate("MainWindow", "Set Pose"))
        self.labelSYaw.setText(_translate("MainWindow", "Y"))
        self.labelSPitch.setText(_translate("MainWindow", "P"))
        self.labelSX.setText(_translate("MainWindow", "X"))
        self.labelSZ.setText(_translate("MainWindow", "Z"))
        self.labelSRoll.setText(_translate("MainWindow", "R"))
        self.labelSY.setText(_translate("MainWindow", "Y"))
        self.labelSPRHand.setText(_translate("MainWindow", "Right Hand"))
        self.labelSPose.setText(_translate("MainWindow", "Pose"))
        self.labelSPLHand.setText(_translate("MainWindow", "Left Hand"))
        self.pushButtonSetRHandPose.setText(_translate("MainWindow", "Set Right Hand Pose"))
        self.pushButtonSetLHandPose.setText(_translate("MainWindow", "Set Left Hand Pose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manipulation), _translate("MainWindow", "Manipulation Module"))
        self.labelHeadYaw.setText(_translate("MainWindow", "Head Yaw"))
        self.labelHeadPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelHeadYawCurrent.setText(_translate("MainWindow", "0"))
        self.labelHeadPitch.setText(_translate("MainWindow", "Head Pitch"))
        self.labelHeadJointValue.setText(_translate("MainWindow", "Value (Rad)"))
        self.labelHeadJointCommand.setText(_translate("MainWindow", "Command (Rad)"))
        self.labelHeadJointName.setText(_translate("MainWindow", "Joint Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_head), _translate("MainWindow", "Head"))
        self.labelLElbowPitch.setText(_translate("MainWindow", "Left Elbow Pitch"))
        self.labelRShoulderRoll.setText(_translate("MainWindow", "Right Shoulder Roll"))
        self.labelLShoulderPitch.setText(_translate("MainWindow", "Left Shoulder Pitch"))
        self.labelLShoulderPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelLShoulderRollCurrent.setText(_translate("MainWindow", "0"))
        self.labelRShoulderPitch.setText(_translate("MainWindow", "Right Shoulder Pitch"))
        self.labelRElbowPitch.setText(_translate("MainWindow", "Right Elbow Pitch"))
        self.labelArmJointName.setText(_translate("MainWindow", "Joint Name"))
        self.labelLShoulderRoll.setText(_translate("MainWindow", "Left Shoulder Roll"))
        self.labelLElbowYaw.setText(_translate("MainWindow", "Left Elbow Yaw"))
        self.labelArmJointValue.setText(_translate("MainWindow", "Value (Rad)"))
        self.labelArmJointCommand.setText(_translate("MainWindow", "Command (Rad)"))
        self.labelRElbowYaw.setText(_translate("MainWindow", "Right Elbow Yaw"))
        self.labelLElbowPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelLElbowYawCurrent.setText(_translate("MainWindow", "0"))
        self.labelRShoulderPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelRShoulderRollCurrent.setText(_translate("MainWindow", "0"))
        self.labelRElbowPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelRElbowYawCurrent.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arm), _translate("MainWindow", "Arm"))
        self.labelLAnklePitch.setText(_translate("MainWindow", "Left Ankle Pitch"))
        self.labelRAnklePitch.setText(_translate("MainWindow", "Right Ankle Pitch"))
        self.labelRHipPitch.setText(_translate("MainWindow", "Right Hip Pitch"))
        self.labelLAnkleRoll.setText(_translate("MainWindow", "Left Ankle Roll"))
        self.labelLHipYaw.setText(_translate("MainWindow", "Left Hip Yaw"))
        self.labelRHipYaw.setText(_translate("MainWindow", "Right Hip Yaw"))
        self.labelLHipRollCurrent.setText(_translate("MainWindow", "0"))
        self.labelLHipPitch.setText(_translate("MainWindow", "Left Hip Pitch"))
        self.labelLegJointValue.setText(_translate("MainWindow", "Value (Rad)"))
        self.labelRHipPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelRHipRoll.setText(_translate("MainWindow", "Right Hip Roll"))
        self.labelRHipRollCurrent.setText(_translate("MainWindow", "0"))
        self.labelRAnklePitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelLegJointName.setText(_translate("MainWindow", "Joint Name"))
        self.labelLHipRoll.setText(_translate("MainWindow", "Left Hip Roll"))
        self.labelLegJointCommand.setText(_translate("MainWindow", "Command (Rad)"))
        self.labelLAnkleRollCurrent.setText(_translate("MainWindow", "0"))
        self.labelLAnklePitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelLHipYawCurrent.setText(_translate("MainWindow", "0"))
        self.labelLHipPitchCurrent.setText(_translate("MainWindow", "0"))
        self.labelRHipYawCurrent.setText(_translate("MainWindow", "0"))
        self.labelRAnkleRoll.setText(_translate("MainWindow", "Right Ankle Roll"))
        self.labelRAnkleRollCurrent.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_leg), _translate("MainWindow", "Leg"))
